schema_version = "1.0.0"
id = "modular_tree"
version = "4.0.2"
name = "Modular Tree"
tagline = "Procedural tree generation using nodes"
maintainer = "Maxime"
type = "add-on"
website = "https://github.com/MaximeHerpin/modular_tree"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later", "SPDX:MIT"]
